authorName: default
experimentName: example
maxExecDuration: 5h
maxTrialNum: 80
searchSpacePath: search_space.json
trainingServicePlatform: local
trial:
  codeDir: .
  command: 'python train_tlp.py --mode train --save_folder=''models/train/tlp_i7_base''
    --under_train_dataset=''./data_model/bert_base_train_and_val.pkl'' --under_test_dataset=''./data_model/bert_base_test.pkl'' '
  gpuNum: 0
trialConcurrency: 1
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
useAnnotation: false
