authorName: default
experimentName: example
maxExecDuration: 1h
maxTrialNum: 150
searchSpacePath: search_space.json
trainingServicePlatform: local
trial:
  codeDir: .
  command: python train_tlp.py --mode deploy --save_folder='models/il/tlp_i7_large'
    --under_model='./models/tlp_model_base_best.pkl' --test_data='./data_model/bert_large_test.pkl'
    --path='((bert_large*.task.pkl'
  gpuNum: 0
trialConcurrency: 1
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
useAnnotation: false
