authorName: default
experimentName: example
maxExecDuration: 4h
maxTrialNum: 150
searchSpacePath: search_space.json
trainingServicePlatform: local
trial:
  codeDir: .
  command: python Loop_de.py --mode train
  gpuNum: 0
trialConcurrency: 1
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
useAnnotation: false
