authorName: default
experimentName: example
maxExecDuration: 15h
maxTrialNum: 150
searchSpacePath: search_space.json
trainingServicePlatform: local
trial:
  codeDir: .
  command: 'python train_tlp.py --mode train --save_folder=''models/tlp_i7_large''
    --under_train_dataset=''./data_model/bert_large_train_and_val.pkl'' --under_test_dataset=''./data_model/bert_large_test.pkl'' '
  gpuNum: 0
trialConcurrency: 1
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
useAnnotation: false
