authorName: default
experimentName: example
maxExecDuration: 5h
maxTrialNum: 150
searchSpacePath: search_space.json
trainingServicePlatform: local
trial:
  codeDir: .
  command: python VD_vulde.py --mode deploy --output_dir=./saved_models     --model_type=roberta     --tokenizer_name=microsoft/codebert-base     --model_name_or_path=microsoft/codebert-base   --do_train  --do_eval     --do_test     --train_data_file=../../../benchmark/Bug/train.jsonl     --eval_data_file=../../../benchmark/Bug/valid.jsonl     --test_data_file=../../../benchmark/Bug/test.jsonl
    --evaluate_during_training
  gpuNum: 0
trialConcurrency: 1
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
useAnnotation: false
