authorName: default
experimentName: example
maxExecDuration: 5h
maxTrialNum: 150
searchSpacePath: search_space.json
trainingServicePlatform: local
trial:
  codeDir: .
  command: python DevM_i2v.py --mode deploy
  gpuNum: 0
trialConcurrency: 1
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
useAnnotation: false
