authorName: default
experimentName: example
maxExecDuration: 1h
maxTrialNum: 300
searchSpacePath: search_space.json
trainingServicePlatform: local
trial:
  codeDir: .
  command: python Thread_magni.py --mode deploy
  gpuNum: 0
trialConcurrency: 1
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
useAnnotation: false
